### PR TITLE
Remove QuoteCharacter option

### LINKED ISSUE #531: Unsafe escaping of log data
I've noticed the output of a program appeared to be broken with logrus, this seems to be due to [appendValue][1].

```
	case string:
		if !f.needsQuoting(value) {
			b.WriteString(value)
		} else {
			fmt.Fprintf(b, "%s%v%s", f.QuoteCharacter, value, f.QuoteCharacter)
		}
```

It seems %v doesn't sufficiently escape the string, I think the else branch should be replaced with:
```
			fmt.Fprintf(b, "%q", value)
```

[1]: https://github.com/sirupsen/logrus/blob/67bca5dc4fe4e689c042885ca5b09e1df1356979/text_formatter.go#L171-L189

### PR DESCRIPTION
**Pull request by dmathieu**
This seems to be one of the most reported issues, as it makes it a lot rarder to safely escape strings.

This option is very much an edge case, and it's causing too much issues compared to what it provide.

Closes #531

cc @sirupsen @bbrks @seiffert @kpcyrd

### CODE REVIEW

File: text_formatter_test.go [hunk 1]
```diff
@@ -72,36 +60,13 @@ func TestEscaping_DefaultQuoteCharacter(t *testing.T) {
...
-}
-
 func TestTimestampFormat(t *testing.T) {
 	checkTimeStr := func(format string) {
 		customFormatter := &TextFormatter{DisableColors: true, TimestampFormat: format}
 		customStr, _ := customFormatter.Format(WithField("test", "test"))
 		timeStart := bytes.Index(customStr, ([]byte)("time="))
 		timeEnd := bytes.Index(customStr, ([]byte)("level="))
-		timeStr := customStr[timeStart+5+len(customFormatter.QuoteCharacter) : timeEnd-1-len(customFormatter.QuoteCharacter)]
+		timeStr := customStr[timeStart+5+len("\"") : timeEnd-1-len("\"")]
```
Comment (PurpureGecko) [inline text_formatter_test.go]: The `len("\"")` always 1. Any reason to not use constant?

Comment (dmathieu) [inline text_formatter_test.go]: No particular reason, no. This is in tests though, there is no huge speed issues.
