### PR TITLE
Fix trailing space

### LINKED ISSUE #99: text log should remove trailing space
current code is generating every log line with a trailing space, which is not good and should be eliminated

``` go
tf := &TextFormatter{DisableColors: true}
byts, _ := tf.Format(&Entry{Message: "msg content"})
fmt.Printf("%q\n", string(byts))
```

``` text
"time=\"0001-01-01T00:00:00Z\" level=panic msg=\"msg content\" \n"
```

### PR DESCRIPTION
**Pull request by dmathieu**
Closes #99

### CODE REVIEW

File: text_formatter.go [hunk 1]
```diff
@@ -154,11 +154,12 @@ func (f *TextFormatter) needsQuoting(text string) bool {
 }
 
 func (f *TextFormatter) appendKeyValue(b *bytes.Buffer, key string, value interface{}) {
-
```
Comment (seiffert) [inline text_formatter.go]: ❤️

File: text_formatter.go [hunk 2]
```diff
@@ -154,11 +154,12 @@ func (f *TextFormatter) needsQuoting(text string) bool {
...
+	if b.String() != "" {
+		b.WriteByte(' ')
```
Comment (seiffert) [inline text_formatter.go]: I wonder whether the buffer could be a string slice (then we could just use `strings.Join()`). However this refactoring is out of scope of this PR an your change definitely does the job!

Comment (dmathieu) [inline text_formatter.go]: We apparently allow it to be any buffer (the client can specify it). So it doesn't seem we could do that without breaking the api.

File: text_formatter.go [hunk 3]
```diff
@@ -154,11 +154,12 @@ func (f *TextFormatter) needsQuoting(text string) bool {
 }
 
 func (f *TextFormatter) appendKeyValue(b *bytes.Buffer, key string, value interface{}) {
-
+	if b.String() != "" {
```
Comment (stevvooe) [inline text_formatter.go]: This is going to cost allocation of the whole buffer. If this is used in a loop, a string will be created when appending each value, generating a lot of garbage for every log message. It would be better to test the length of the buffer.

Comment (dmathieu) [inline text_formatter.go]: Good idea. Do you want to open a PR?

Comment (stevvooe) [inline text_formatter.go]: I'm not sure if I have time today, but it would be good to get this fixed.
