### PR TITLE
Fix caller package name

### LINKED ISSUE #1089: Report Caller returns logrus files/functions with Go 1.14Beta1
In Go 1.14Beta1, the file and function information logged when ReportCaller is set to true reports logrus code, not the calling code.

## POC

```go
package main

import "github.com/sirupsen/logrus"

func init() {
	logrus.SetReportCaller(true)
	logrus.Info("Logging from init")
}

func main() {
	logrus.Info("Logging from main")
	foo()
}

func foo() {
	logrus.Info("Logging from foo")
}
```

### 1.13.6 Output
INFO[0000]/tmp/poc/main.go:7 main.init.0() Logging from init                            
INFO[0000]/tmp/poc/main.go:13 main.main() Logging from main                            
INFO[0000]/tmp/poc/main.go:19 main.foo() Logging from foo

### 1.14Beta1 Output
INFO[0000]/home/nzb301/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Logging from init                            
INFO[0000]/home/nzb301/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Logging from main                            
INFO[0000]/home/nzb301/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Logging from foo

### PR DESCRIPTION
**Pull request by hlcfan**
Fix #1089 

This is identical to https://github.com/sirupsen/logrus/pull/1099

### CODE REVIEW

**Comment by thaJeztah** [comment]
Should there be different implementations for Go < 1.14, and Go 1.14 and up?

**Comment by hlcfan** [comment]
I think https://go-review.googlesource.com/c/go/+/219118/ should be related.

**Comment by thaJeztah** [comment]
> I think https://go-review.googlesource.com/c/go/+/219118/ should be related.

That indicates it should be fixed in the go1.14 final? Is this still an issue in go1.14 (non-rc?)

File: entry.go [hunk 1]
```diff
@@ -419,3 +426,7 @@ func (entry *Entry) sprintlnn(args ...interface{}) string {
 	msg := fmt.Sprintln(args...)
 	return msg[:len(msg)-1]
 }
+
+func golang1_14() bool {
+	return strings.HasPrefix(runtime.Version(), goVersion1_14)
```
Comment (thaJeztah) [inline entry.go]: If this fix is still needed on go1.14 final, it's cleaner to use build tags for this instead of determining go version at runtime; have a file that has a `!go1.14` build-tag  for older go versions, and an implementation in a file with a `go1.14` build-tag for the current version.

See https://github.com/docker/go-connections/pull/68/files for an example

Comment (hlcfan) [reply entry.go]: 👍  Updated, please review again.

**Comment by thaJeztah** [comment]
Thanks! Last version SGTM (but haven't checked on both go1.13 and go1.14 final)

**Comment by hlcfan** [comment]
> > I think https://go-review.googlesource.com/c/go/+/219118/ should be related.
> 
> That indicates it should be fixed in the go1.14 final? Is this still an issue in go1.14 (non-rc?)

I was wrong, that cl wasn't related 😅

**Comment by ergoz** [comment]
when it will be merged? this bug is critical for me and my colleagues

**Comment by dgsb** [comment]
Thanks for your contributions

**Comment by ergoz** [comment]
thanks for fix!
when new tag will be released?
