### PR TITLE
Remove colored output on windows

### LINKED ISSUE #862: Colorized output on windows 7 broken
When printing output with a TextFormatter to cmd or powershell on windows 7, the control sequences are rendered to the output.

``←[36mINFO←[0m[0000] Replay took: 4.0003ms                         ←[36msource←[0m=Badger``

This was already mentioned in #820 but probably never investigated.

Workaround: Just disable colors with 

```
log.SetFormatter(&logrus.TextFormatter{
		DisableColors: true,
})
```

### PR DESCRIPTION
**Pull request by ceriath**
Fixes #862

Currently the textformatter on windows outputs 

``←[31mERRO←[0m[0000] test windows``

when coloring is not disabled explicitly.
However, windows up to windows 8.1 does not support colored output on cmd entirely. Windows 10 added support for it, which is off by default and has to be enabled via registry or environment variable. Therefore i suggest removing colored output on windows entirely to make the output usable again.

### CODE REVIEW

File: text_formatter.go [hunk 1]
```diff
@@ -102,7 +103,7 @@ func (f *TextFormatter) isColored() bool {
 		}
 	}
 
-	return isColored && !f.DisableColors
+	return isColored && !f.DisableColors && (runtime.GOOS != "windows")
```
Comment (dgsb) [inline text_formatter.go]: Hello, I would like that the ForceColor field of the text formatter takes precedence on the environment check.
I expect that then this flag is set to true the user knows what he is doing.

File: text_formatter_test.go [hunk 2]
```diff
@@ -443,7 +444,11 @@ func TestTextFormatterIsColored(t *testing.T) {
 				os.Setenv("CLICOLOR_FORCE", val.clicolorForceVal)
 			}
 			res := tf.isColored()
-			assert.Equal(subT, val.expectedResult, res)
+			if runtime.GOOS == "windows" {
```
Comment (dgsb) [inline text_formatter_test.go]: I think we need to updated the test  for windows environment where isColored always return false except when ForceColor is set to true.

**Comment by dgsb** [comment]
@ceriath thanks for your contribution, I've added a few comments on you change. Let me know what you think.

**Comment by ceriath** [comment]
@dgsb i agree, i changed it so setting ForceColor or the environment variables takes precedence. With the environment variables users who explicitly turned on colored output have an easy way to also enable it on logrus without recompiling the application

**Comment by dgsb** [comment]
@ceriath that's exactly what I had in mind.
